name: clinicconnect
region: nyc

services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/clinicconnect-2
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile.optimized
    
    http_port: 5001
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    health_check:
      http_path: /api/health
      initial_delay_seconds: 40
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      
      - key: PORT
        value: "5001"
        scope: RUN_TIME
      
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
        type: SECRET
      
      - key: JWT_SECRET
        value: YOUR_JWT_SECRET_HERE
        scope: RUN_TIME
        type: SECRET
      
      - key: SESSION_SECRET
        value: YOUR_SESSION_SECRET_HERE
        scope: RUN_TIME
        type: SECRET
      
      - key: SESSION_COOKIE_MAX_AGE
        value: "2592000000"
        scope: RUN_TIME
      
      - key: ALLOWED_ORIGINS
        value: https://your-app-name.ondigitalocean.app
        scope: RUN_TIME

databases:
  - name: clinicconnect-db
    engine: PG
    version: "16"
    production: false
    cluster_name: clinicconnect-db-cluster

